- Up for 3.1-RC5.
Changed files:
    kdebase-startkde.patch -> 1.1.2.3

diff --git a/kdebase-startkde.patch b/kdebase-startkde.patch
--- a/kdebase-startkde.patch
+++ b/kdebase-startkde.patch
@@ -1,7 +1,15 @@
-diff -urN kdebase-3.0beta2.orig/startkde kdebase-3.0beta2/startkde
---- kdebase-3.0beta2.orig/startkde	Sat Feb  9 02:59:15 2002
-+++ kdebase-3.0beta2/startkde	Wed Feb 20 20:15:36 2002
-@@ -20,6 +20,19 @@
+--- kdebase-3.1.orig/startkde	Mon Nov 25 01:45:51 2002
++++ kdebase-3.1/startkde	Fri Nov 29 17:32:56 2002
+@@ -5,7 +5,7 @@
+ 
+ # When the X server dies we get a SIGHUP from xinit. We must ignore it
+ # because we still need to do some cleanup.
+-trap 'echo GOT SIGHUP' SIGHUP
++trap 'echo GOT SIGHUP' HUP
+ 
+ # Boot sequence:
+ #
+@@ -24,6 +24,19 @@
  #   2) everything in $KDEDIR/share/autostart (kdesktop, kicker, etc.)
  #   3) the rest of the session.
  
@@ -21,9 +29,9 @@ diff -urN kdebase-3.0beta2.orig/startkde kdebase-3.0beta2/startkde
  # Set a left cursor instead of the standard X11 "X" cursor, since I've heard
  # from some users that they're confused and don't know what to do. This is
  # especially necessary on slow machines, where starting KDE takes one or two
-@@ -39,70 +52,6 @@
+@@ -43,72 +56,6 @@
  kdehome=$HOME/.kde
- test -n "$KDEHOME" && eval kdehome=$KDEHOME
+ test -n "$KDEHOME" && kdehome=`echo "$KDEHOME"|sed "s,^\~/,$HOME/,"`
  
 -# Activate the kde font directories.
 -#
@@ -45,7 +53,7 @@ diff -urN kdebase-3.0beta2.orig/startkde kdebase-3.0beta2/startkde
 -usr_odir=$kdehome/share/fonts/override
 -usr_fdir=$kdehome/share/fonts
 -if test -n "$KDEDIRS"; then
--  kdedirs_first=`echo $KDEDIRS|sed -e 's/:.*//'`
+-  kdedirs_first=`echo "$KDEDIRS"|sed -e 's/:.*//'`
 -  sys_odir=$kdedirs_first/share/fonts/override
 -  sys_fdir=$kdedirs_first/share/fonts
 -else
@@ -58,22 +66,25 @@ diff -urN kdebase-3.0beta2.orig/startkde kdebase-3.0beta2/startkde
 -# add the user's dirs to the font path, as they might simply have been made
 -# read-only by the administrator, for whatever reason.
 -
--test -d $usr_odir && (mkfontdir $usr_odir ; xset +fp $usr_odir)
--test -d $sys_odir && xset +fp $sys_odir
--test -d $usr_fdir && (mkfontdir $usr_fdir ; xset fp+ $usr_fdir)
--test -d $sys_fdir && xset fp+ $sys_fdir
+-test -d "$usr_odir" && (mkfontdir "$usr_odir" ; xset +fp "$usr_odir")
+-test -d "$sys_odir" && xset +fp "$sys_odir"
+-test -d "$usr_fdir" && (mkfontdir "$usr_fdir" ; xset fp+ "$usr_fdir")
+-test -d "$sys_fdir" && xset fp+ "$sys_fdir"
 -
 -#
 -# Add any user-installed font directories to the X font path
 -kde_fontsdir=$kdehome/share/fonts
 -kde_fontpaths=$kde_fontsdir/fontpaths
-- 
--if test -r $kde_fontpaths ; then
--    for fpath in `cat $kde_fontpaths | grep -v '#'` ; do
--        if test -s $fpath/fonts.dir ; then
--            xset fp+ $fpath
+-
+-if test -r "$kde_fontpaths" ; then
+-    savifs=$IFS
+-    IFS=
+-    for fpath in `grep -v '^[ 	]*#' < "$kde_fontpaths"` ; do
+-        if test -s "$fpath"/fonts.dir ; then
+-            xset fp+ "$fpath"
 -        fi
 -    done
+-    IFS=$savifs
 -fi
 -
 -# Ask X11 to rebuild its font list.
@@ -88,21 +99,6 @@ diff -urN kdebase-3.0beta2.orig/startkde kdebase-3.0beta2/startkde
 -    GS_LIB=$kde_fontsdir
 -    export GS_LIB
 -fi
--
+ 
  # Link "tmp" resource to directory in /tmp
  # Creates a directory /tmp/kde-$USER and links $KDEHOME/tmp-$HOSTNAME to it.
- lnusertemp tmp >/dev/null
-@@ -142,8 +91,11 @@
- # if no windowmanager is specified, ksmserver will ensure kwin is started.
- # [--restore] should be controlled by kdm
- # kwrapper is used to reduce startup time and memory usage
--kwrapper ksmserver --restore || \
--  xmessage -geometry 500x100 "Couldn't start ksmserver. Check your installation."
-+if [ $# -eq 1 ]; then
-+	kwrapper ksmserver --windowmanager $1
-+else
-+	kwrapper ksmserver --restore
-+fi
- 
- # Clean up
- kdeinit_shutdown
